services:
    db:
        image: postgres:15-alpine
        container_name: postgres_db
        restart: unless-stopped
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: movie_host
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - movie-host-network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U user -d movie_host"]
            interval: 5s
            timeout: 5s
            retries: 5

    server:
        build: ./server
        develop:
            watch:
                - action: rebuild
                  path: ./server/src
                - action: rebuild
                  path: ./server/Cargo.toml
        container_name: movie-host-api
        restart: unless-stopped
        depends_on:
            db:
                condition: service_healthy
        ports:
            - '3000:3000'
        pid: 'host'
        networks:
            - movie-host-network
        volumes:
            - '${MEDIA_HOME}:/media'
        environment:
            - API_PORT=3000
            - SERVE_DIR=/media
            - DATABASE_URL=postgresql://user:password@db:5432/movie_host

    frontend:
        build: ./frontend
        develop:
            watch:
                - action: sync
                  path: ./frontend/src
                  target: /app/src
                - action: rebuild
                  path: ./frontend/package.json
        container_name: movie-host-frontend
        restart: unless-stopped
        ports:
            - '3001:80'
        depends_on:
            - server
        networks:
            - movie-host-network
        environment:
            - NODE_ENV=production

networks:
    movie-host-network:
        driver: bridge

volumes:
    pgdata:
