services:
  frontend:
    build:
      context: ./frontend
      target: builder
    command: npm run dev -- --port 80
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - API_URL=http://server:3000
