[package]
name = "server"
version = "1.0.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.9", features = ["ws"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.2", features = ["full"] }
tower-http = {version = "0.7.1", default-features = false, features = ["cors", "fs"]}
walkdir = "2.5.0"
sqlx = { version = "0.9", features = ["runtime-tokio", "tls-rustls", "postgres", "macros"] }
futures-util = "0.3"
reqwest = "0.13.5"
utoipa = { version = "6.0.0", features = ["axum_extras"] }
utoipa-axum = "0.3.0"
utoipa-scalar = { version = "0.4.0", features = ["axum"] }

[profile.release]
lto = true
codegen-units = 1